package obfuscator;

public enum ObfRule {
    MAP_CLASS,
    MAP_METHOD,
    MAP_FIELD,
    MAP_LOCALVARS,
    ANTI_DEBUG,
    CONTROL_FLOW_FLATTENING,
    EXCEPTIONS,
    GARBAGE_INJECT,
    OPAQUE_PREDICATE,
    OBF_PRIMITIVES,
    STACK_ABUSE,
    OBF_STRING,
    STRUCTURAL,
    SWITCH_BOMB,
}