package obfuscator;

public enum ObfRule {
    MAP_CLASS,
    MAP_METHOD,
    MAP_FIELD,
    MAP_LOCALVARS,
    OBF_STRING,
    OBF_PRIMITIVES,
    CONTROL_FLOW_FLATTENING,
    OPAQUE_PREDICATE,
    STACK_ABUSE,
    EXCEPTIONS,
    SWITCH_BOMB,
    GARBAGE_INJECT,
    STRUCTURAL
}