package obfuscator;

public enum ObfRule {
    RENAME_CLASS,
    RENAME_METHOD,
    RENAME_FIELD,
    RENAME_LOCALVARS,

    OBFUSCATE_CODE,
    OBFUSCATE_STRINGS,
    OBFUSCATE_PRIMITIVES,

    CONTROL_FLOW,
    OPAQUE_PREDICATE,
    STACK_ABUSE,
    EXCEPTIONS,
    SWITCH_BOMB,

    GARBAGE,
    STRUCTURE
}