name: Build Hm

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21' # <- Изменено с 17 на 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mod-Jar-File
          path: build/libs/*.jar
